-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 17:30:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_Reserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_Reserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_Reserva` DEFAULT CHARACTER SET utf8 ;
USE `BD_Reserva` ;

-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_quartos` (
  `id_quartos` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `andar` VARCHAR(3) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `preco_diaria` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `tipo_quarto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_quartos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `nome_pai` VARCHAR(100) NULL,
  `nome_mae` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `num_documento` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_clientes` (
  `id_usuario` INT NOT NULL,
  `cod_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_funcionarios` (
  `id_usuario` INT NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `acesso` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `estado` VARCHAR(1) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `unidade_medida` VARCHAR(45) NULL,
  `preco_venda` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_quartos` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  `tipo_reserva` VARCHAR(45) NOT NULL,
  `data_reserva` DATE NULL,
  `data_entrada` DATE NULL,
  `data_saida` DATE NULL,
  `valor_quarto` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_consumo` (
  `id_consumo` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` DECIMAL(7,2) NOT NULL,
  `preco_venda` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_consumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Reserva`.`tb_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Reserva`.`tb_pagamentos` (
  `id_pagamentos` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` VARCHAR(45) NOT NULL,
  `tipo_comprovante` VARCHAR(45) NOT NULL,
  `taxa` DECIMAL(4,2) NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_pagamento` DATE NOT NULL,
  PRIMARY KEY (`id_pagamentos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
